// Code generated by "enumer -type ResourceType -addprefix azurerm_ -transform snake -linecomment"; DO NOT EDIT.

package azurerm

import (
	"fmt"
)

const _ResourceTypeName = "azurerm_resource_groupazurerm_virtual_machineazurerm_virtual_networkazurerm_subnetazurerm_network_interfaceazurerm_network_security_groupazurerm_virtual_machine_scale_set"

var _ResourceTypeIndex = [...]uint8{0, 22, 45, 68, 82, 107, 137, 170}

const _ResourceTypeLowerName = "azurerm_resource_groupazurerm_virtual_machineazurerm_virtual_networkazurerm_subnetazurerm_network_interfaceazurerm_network_security_groupazurerm_virtual_machine_scale_set"

func (i ResourceType) String() string {
	if i < 0 || i >= ResourceType(len(_ResourceTypeIndex)-1) {
		return fmt.Sprintf("ResourceType(%d)", i)
	}
	return _ResourceTypeName[_ResourceTypeIndex[i]:_ResourceTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ResourceTypeNoOp() {
	var x [1]struct{}
	_ = x[ResourceGroup-(0)]
	_ = x[VirtualMachine-(1)]
	_ = x[VirtualNetwork-(2)]
	_ = x[Subnet-(3)]
	_ = x[NetworkInterface-(4)]
	_ = x[NetworkSecurityGroup-(5)]
	_ = x[VirtualMachineScaleSet-(6)]
}

var _ResourceTypeValues = []ResourceType{ResourceGroup, VirtualMachine, VirtualNetwork, Subnet, NetworkInterface, NetworkSecurityGroup, VirtualMachineScaleSet}

var _ResourceTypeNameToValueMap = map[string]ResourceType{
	_ResourceTypeName[0:22]:         ResourceGroup,
	_ResourceTypeLowerName[0:22]:    ResourceGroup,
	_ResourceTypeName[22:45]:        VirtualMachine,
	_ResourceTypeLowerName[22:45]:   VirtualMachine,
	_ResourceTypeName[45:68]:        VirtualNetwork,
	_ResourceTypeLowerName[45:68]:   VirtualNetwork,
	_ResourceTypeName[68:82]:        Subnet,
	_ResourceTypeLowerName[68:82]:   Subnet,
	_ResourceTypeName[82:107]:       NetworkInterface,
	_ResourceTypeLowerName[82:107]:  NetworkInterface,
	_ResourceTypeName[107:137]:      NetworkSecurityGroup,
	_ResourceTypeLowerName[107:137]: NetworkSecurityGroup,
	_ResourceTypeName[137:170]:      VirtualMachineScaleSet,
	_ResourceTypeLowerName[137:170]: VirtualMachineScaleSet,
}

var _ResourceTypeNames = []string{
	_ResourceTypeName[0:22],
	_ResourceTypeName[22:45],
	_ResourceTypeName[45:68],
	_ResourceTypeName[68:82],
	_ResourceTypeName[82:107],
	_ResourceTypeName[107:137],
	_ResourceTypeName[137:170],
}

// ResourceTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ResourceTypeString(s string) (ResourceType, error) {
	if val, ok := _ResourceTypeNameToValueMap[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ResourceType values", s)
}

// ResourceTypeValues returns all values of the enum
func ResourceTypeValues() []ResourceType {
	return _ResourceTypeValues
}

// ResourceTypeStrings returns a slice of all String values of the enum
func ResourceTypeStrings() []string {
	strs := make([]string, len(_ResourceTypeNames))
	copy(strs, _ResourceTypeNames)
	return strs
}

// IsAResourceType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ResourceType) IsAResourceType() bool {
	for _, v := range _ResourceTypeValues {
		if i == v {
			return true
		}
	}
	return false
}
