// Code generated by "enumer -type ResourceType -addprefix aws_ -transform snake -linecomment"; DO NOT EDIT.

package aws

import (
	"fmt"
)

const _ResourceTypeName = "aws_instanceaws_vpcaws_security_groupaws_subnetaws_ebs_volumeaws_elasticache_clusteraws_elbaws_albaws_db_instanceaws_s3_bucketaws_cloudfront_distributionaws_cloudfront_origin_access_identityaws_cloudfront_public_keyaws_iam_access_keyaws_iam_account_aliasaws_iam_account_password_policyaws_iam_groupaws_iam_group_membershipaws_iam_group_policyaws_iam_group_policy_attachmentaws_iam_instance_profileaws_iam_openid_connect_provideraws_iam_policyaws_iam_roleaws_iam_role_policyaws_iam_role_policy_attachmentaws_iam_saml_provideraws_iam_server_certificateaws_iam_useraws_iam_user_group_membershipaws_iam_user_policyaws_iam_user_policy_attachmentaws_route53_delegation_setaws_route53_health_checkaws_route53_query_logaws_route53_recordaws_route53_zoneaws_route53_zone_associationaws_route53_resolver_endpointaws_route53_resolver_rule_associationaws_ses_active_receipt_rule_setaws_ses_domain_identityaws_ses_domain_identity_verificationaws_ses_domain_dkimaws_ses_domain_mail_fromaws_ses_receipt_filteraws_ses_receipt_ruleaws_ses_receipt_rule_setaws_ses_configuration_setaws_ses_identity_notification_topicaws_ses_template"

var _ResourceTypeIndex = [...]uint16{0, 12, 19, 37, 47, 61, 84, 91, 98, 113, 126, 153, 190, 215, 233, 254, 285, 298, 322, 342, 373, 397, 428, 442, 454, 473, 503, 524, 550, 562, 591, 610, 640, 666, 690, 711, 729, 745, 773, 802, 839, 870, 893, 929, 948, 972, 994, 1014, 1038, 1063, 1098, 1114}

const _ResourceTypeLowerName = "aws_instanceaws_vpcaws_security_groupaws_subnetaws_ebs_volumeaws_elasticache_clusteraws_elbaws_albaws_db_instanceaws_s3_bucketaws_cloudfront_distributionaws_cloudfront_origin_access_identityaws_cloudfront_public_keyaws_iam_access_keyaws_iam_account_aliasaws_iam_account_password_policyaws_iam_groupaws_iam_group_membershipaws_iam_group_policyaws_iam_group_policy_attachmentaws_iam_instance_profileaws_iam_openid_connect_provideraws_iam_policyaws_iam_roleaws_iam_role_policyaws_iam_role_policy_attachmentaws_iam_saml_provideraws_iam_server_certificateaws_iam_useraws_iam_user_group_membershipaws_iam_user_policyaws_iam_user_policy_attachmentaws_route53_delegation_setaws_route53_health_checkaws_route53_query_logaws_route53_recordaws_route53_zoneaws_route53_zone_associationaws_route53_resolver_endpointaws_route53_resolver_rule_associationaws_ses_active_receipt_rule_setaws_ses_domain_identityaws_ses_domain_identity_verificationaws_ses_domain_dkimaws_ses_domain_mail_fromaws_ses_receipt_filteraws_ses_receipt_ruleaws_ses_receipt_rule_setaws_ses_configuration_setaws_ses_identity_notification_topicaws_ses_template"

func (i ResourceType) String() string {
	i -= 1
	if i < 0 || i >= ResourceType(len(_ResourceTypeIndex)-1) {
		return fmt.Sprintf("ResourceType(%d)", i+1)
	}
	return _ResourceTypeName[_ResourceTypeIndex[i]:_ResourceTypeIndex[i+1]]
}

var _ResourceTypeValues = []ResourceType{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51}

var _ResourceTypeNameToValueMap = map[string]ResourceType{
	_ResourceTypeName[0:12]:           1,
	_ResourceTypeLowerName[0:12]:      1,
	_ResourceTypeName[12:19]:          2,
	_ResourceTypeLowerName[12:19]:     2,
	_ResourceTypeName[19:37]:          3,
	_ResourceTypeLowerName[19:37]:     3,
	_ResourceTypeName[37:47]:          4,
	_ResourceTypeLowerName[37:47]:     4,
	_ResourceTypeName[47:61]:          5,
	_ResourceTypeLowerName[47:61]:     5,
	_ResourceTypeName[61:84]:          6,
	_ResourceTypeLowerName[61:84]:     6,
	_ResourceTypeName[84:91]:          7,
	_ResourceTypeLowerName[84:91]:     7,
	_ResourceTypeName[91:98]:          8,
	_ResourceTypeLowerName[91:98]:     8,
	_ResourceTypeName[98:113]:         9,
	_ResourceTypeLowerName[98:113]:    9,
	_ResourceTypeName[113:126]:        10,
	_ResourceTypeLowerName[113:126]:   10,
	_ResourceTypeName[126:153]:        11,
	_ResourceTypeLowerName[126:153]:   11,
	_ResourceTypeName[153:190]:        12,
	_ResourceTypeLowerName[153:190]:   12,
	_ResourceTypeName[190:215]:        13,
	_ResourceTypeLowerName[190:215]:   13,
	_ResourceTypeName[215:233]:        14,
	_ResourceTypeLowerName[215:233]:   14,
	_ResourceTypeName[233:254]:        15,
	_ResourceTypeLowerName[233:254]:   15,
	_ResourceTypeName[254:285]:        16,
	_ResourceTypeLowerName[254:285]:   16,
	_ResourceTypeName[285:298]:        17,
	_ResourceTypeLowerName[285:298]:   17,
	_ResourceTypeName[298:322]:        18,
	_ResourceTypeLowerName[298:322]:   18,
	_ResourceTypeName[322:342]:        19,
	_ResourceTypeLowerName[322:342]:   19,
	_ResourceTypeName[342:373]:        20,
	_ResourceTypeLowerName[342:373]:   20,
	_ResourceTypeName[373:397]:        21,
	_ResourceTypeLowerName[373:397]:   21,
	_ResourceTypeName[397:428]:        22,
	_ResourceTypeLowerName[397:428]:   22,
	_ResourceTypeName[428:442]:        23,
	_ResourceTypeLowerName[428:442]:   23,
	_ResourceTypeName[442:454]:        24,
	_ResourceTypeLowerName[442:454]:   24,
	_ResourceTypeName[454:473]:        25,
	_ResourceTypeLowerName[454:473]:   25,
	_ResourceTypeName[473:503]:        26,
	_ResourceTypeLowerName[473:503]:   26,
	_ResourceTypeName[503:524]:        27,
	_ResourceTypeLowerName[503:524]:   27,
	_ResourceTypeName[524:550]:        28,
	_ResourceTypeLowerName[524:550]:   28,
	_ResourceTypeName[550:562]:        29,
	_ResourceTypeLowerName[550:562]:   29,
	_ResourceTypeName[562:591]:        30,
	_ResourceTypeLowerName[562:591]:   30,
	_ResourceTypeName[591:610]:        31,
	_ResourceTypeLowerName[591:610]:   31,
	_ResourceTypeName[610:640]:        32,
	_ResourceTypeLowerName[610:640]:   32,
	_ResourceTypeName[640:666]:        33,
	_ResourceTypeLowerName[640:666]:   33,
	_ResourceTypeName[666:690]:        34,
	_ResourceTypeLowerName[666:690]:   34,
	_ResourceTypeName[690:711]:        35,
	_ResourceTypeLowerName[690:711]:   35,
	_ResourceTypeName[711:729]:        36,
	_ResourceTypeLowerName[711:729]:   36,
	_ResourceTypeName[729:745]:        37,
	_ResourceTypeLowerName[729:745]:   37,
	_ResourceTypeName[745:773]:        38,
	_ResourceTypeLowerName[745:773]:   38,
	_ResourceTypeName[773:802]:        39,
	_ResourceTypeLowerName[773:802]:   39,
	_ResourceTypeName[802:839]:        40,
	_ResourceTypeLowerName[802:839]:   40,
	_ResourceTypeName[839:870]:        41,
	_ResourceTypeLowerName[839:870]:   41,
	_ResourceTypeName[870:893]:        42,
	_ResourceTypeLowerName[870:893]:   42,
	_ResourceTypeName[893:929]:        43,
	_ResourceTypeLowerName[893:929]:   43,
	_ResourceTypeName[929:948]:        44,
	_ResourceTypeLowerName[929:948]:   44,
	_ResourceTypeName[948:972]:        45,
	_ResourceTypeLowerName[948:972]:   45,
	_ResourceTypeName[972:994]:        46,
	_ResourceTypeLowerName[972:994]:   46,
	_ResourceTypeName[994:1014]:       47,
	_ResourceTypeLowerName[994:1014]:  47,
	_ResourceTypeName[1014:1038]:      48,
	_ResourceTypeLowerName[1014:1038]: 48,
	_ResourceTypeName[1038:1063]:      49,
	_ResourceTypeLowerName[1038:1063]: 49,
	_ResourceTypeName[1063:1098]:      50,
	_ResourceTypeLowerName[1063:1098]: 50,
	_ResourceTypeName[1098:1114]:      51,
	_ResourceTypeLowerName[1098:1114]: 51,
}

var _ResourceTypeNames = []string{
	_ResourceTypeName[0:12],
	_ResourceTypeName[12:19],
	_ResourceTypeName[19:37],
	_ResourceTypeName[37:47],
	_ResourceTypeName[47:61],
	_ResourceTypeName[61:84],
	_ResourceTypeName[84:91],
	_ResourceTypeName[91:98],
	_ResourceTypeName[98:113],
	_ResourceTypeName[113:126],
	_ResourceTypeName[126:153],
	_ResourceTypeName[153:190],
	_ResourceTypeName[190:215],
	_ResourceTypeName[215:233],
	_ResourceTypeName[233:254],
	_ResourceTypeName[254:285],
	_ResourceTypeName[285:298],
	_ResourceTypeName[298:322],
	_ResourceTypeName[322:342],
	_ResourceTypeName[342:373],
	_ResourceTypeName[373:397],
	_ResourceTypeName[397:428],
	_ResourceTypeName[428:442],
	_ResourceTypeName[442:454],
	_ResourceTypeName[454:473],
	_ResourceTypeName[473:503],
	_ResourceTypeName[503:524],
	_ResourceTypeName[524:550],
	_ResourceTypeName[550:562],
	_ResourceTypeName[562:591],
	_ResourceTypeName[591:610],
	_ResourceTypeName[610:640],
	_ResourceTypeName[640:666],
	_ResourceTypeName[666:690],
	_ResourceTypeName[690:711],
	_ResourceTypeName[711:729],
	_ResourceTypeName[729:745],
	_ResourceTypeName[745:773],
	_ResourceTypeName[773:802],
	_ResourceTypeName[802:839],
	_ResourceTypeName[839:870],
	_ResourceTypeName[870:893],
	_ResourceTypeName[893:929],
	_ResourceTypeName[929:948],
	_ResourceTypeName[948:972],
	_ResourceTypeName[972:994],
	_ResourceTypeName[994:1014],
	_ResourceTypeName[1014:1038],
	_ResourceTypeName[1038:1063],
	_ResourceTypeName[1063:1098],
	_ResourceTypeName[1098:1114],
}

// ResourceTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ResourceTypeString(s string) (ResourceType, error) {
	if val, ok := _ResourceTypeNameToValueMap[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ResourceType values", s)
}

// ResourceTypeValues returns all values of the enum
func ResourceTypeValues() []ResourceType {
	return _ResourceTypeValues
}

// ResourceTypeStrings returns a slice of all String values of the enum
func ResourceTypeStrings() []string {
	strs := make([]string, len(_ResourceTypeNames))
	copy(strs, _ResourceTypeNames)
	return strs
}

// IsAResourceType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ResourceType) IsAResourceType() bool {
	for _, v := range _ResourceTypeValues {
		if i == v {
			return true
		}
	}
	return false
}
