package provider

import (
	"github.com/hashicorp/terraform-provider-azurerm/sdk"
	"github.com/hashicorp/terraform-provider-azurerm/services/aadb2c"
	"github.com/hashicorp/terraform-provider-azurerm/services/advisor"
	"github.com/hashicorp/terraform-provider-azurerm/services/analysisservices"
	"github.com/hashicorp/terraform-provider-azurerm/services/apimanagement"
	"github.com/hashicorp/terraform-provider-azurerm/services/appconfiguration"
	"github.com/hashicorp/terraform-provider-azurerm/services/applicationinsights"
	"github.com/hashicorp/terraform-provider-azurerm/services/appservice"
	"github.com/hashicorp/terraform-provider-azurerm/services/attestation"
	"github.com/hashicorp/terraform-provider-azurerm/services/authorization"
	"github.com/hashicorp/terraform-provider-azurerm/services/automation"
	"github.com/hashicorp/terraform-provider-azurerm/services/azurestackhci"
	"github.com/hashicorp/terraform-provider-azurerm/services/batch"
	"github.com/hashicorp/terraform-provider-azurerm/services/billing"
	"github.com/hashicorp/terraform-provider-azurerm/services/blueprints"
	"github.com/hashicorp/terraform-provider-azurerm/services/bot"
	"github.com/hashicorp/terraform-provider-azurerm/services/cdn"
	"github.com/hashicorp/terraform-provider-azurerm/services/cognitive"
	"github.com/hashicorp/terraform-provider-azurerm/services/communication"
	"github.com/hashicorp/terraform-provider-azurerm/services/compute"
	"github.com/hashicorp/terraform-provider-azurerm/services/confidentialledger"
	"github.com/hashicorp/terraform-provider-azurerm/services/connections"
	"github.com/hashicorp/terraform-provider-azurerm/services/consumption"
	"github.com/hashicorp/terraform-provider-azurerm/services/containers"
	"github.com/hashicorp/terraform-provider-azurerm/services/cosmos"
	"github.com/hashicorp/terraform-provider-azurerm/services/costmanagement"
	"github.com/hashicorp/terraform-provider-azurerm/services/customproviders"
	"github.com/hashicorp/terraform-provider-azurerm/services/databasemigration"
	"github.com/hashicorp/terraform-provider-azurerm/services/databoxedge"
	"github.com/hashicorp/terraform-provider-azurerm/services/databricks"
	"github.com/hashicorp/terraform-provider-azurerm/services/datafactory"
	"github.com/hashicorp/terraform-provider-azurerm/services/dataprotection"
	"github.com/hashicorp/terraform-provider-azurerm/services/datashare"
	"github.com/hashicorp/terraform-provider-azurerm/services/desktopvirtualization"
	"github.com/hashicorp/terraform-provider-azurerm/services/devtestlabs"
	"github.com/hashicorp/terraform-provider-azurerm/services/digitaltwins"
	"github.com/hashicorp/terraform-provider-azurerm/services/disks"
	"github.com/hashicorp/terraform-provider-azurerm/services/dns"
	"github.com/hashicorp/terraform-provider-azurerm/services/domainservices"
	"github.com/hashicorp/terraform-provider-azurerm/services/elastic"
	"github.com/hashicorp/terraform-provider-azurerm/services/eventgrid"
	"github.com/hashicorp/terraform-provider-azurerm/services/eventhub"
	"github.com/hashicorp/terraform-provider-azurerm/services/firewall"
	"github.com/hashicorp/terraform-provider-azurerm/services/frontdoor"
	"github.com/hashicorp/terraform-provider-azurerm/services/hdinsight"
	"github.com/hashicorp/terraform-provider-azurerm/services/healthcare"
	"github.com/hashicorp/terraform-provider-azurerm/services/hpccache"
	"github.com/hashicorp/terraform-provider-azurerm/services/hsm"
	"github.com/hashicorp/terraform-provider-azurerm/services/iotcentral"
	"github.com/hashicorp/terraform-provider-azurerm/services/iothub"
	"github.com/hashicorp/terraform-provider-azurerm/services/iottimeseriesinsights"
	"github.com/hashicorp/terraform-provider-azurerm/services/keyvault"
	"github.com/hashicorp/terraform-provider-azurerm/services/kusto"
	"github.com/hashicorp/terraform-provider-azurerm/services/legacy"
	"github.com/hashicorp/terraform-provider-azurerm/services/lighthouse"
	"github.com/hashicorp/terraform-provider-azurerm/services/loadbalancer"
	"github.com/hashicorp/terraform-provider-azurerm/services/loadtest"
	"github.com/hashicorp/terraform-provider-azurerm/services/loganalytics"
	"github.com/hashicorp/terraform-provider-azurerm/services/logic"
	"github.com/hashicorp/terraform-provider-azurerm/services/logz"
	"github.com/hashicorp/terraform-provider-azurerm/services/machinelearning"
	"github.com/hashicorp/terraform-provider-azurerm/services/maintenance"
	"github.com/hashicorp/terraform-provider-azurerm/services/managedapplications"
	"github.com/hashicorp/terraform-provider-azurerm/services/managementgroup"
	"github.com/hashicorp/terraform-provider-azurerm/services/maps"
	"github.com/hashicorp/terraform-provider-azurerm/services/mariadb"
	"github.com/hashicorp/terraform-provider-azurerm/services/media"
	"github.com/hashicorp/terraform-provider-azurerm/services/mixedreality"
	"github.com/hashicorp/terraform-provider-azurerm/services/monitor"
	"github.com/hashicorp/terraform-provider-azurerm/services/msi"
	"github.com/hashicorp/terraform-provider-azurerm/services/mssql"
	"github.com/hashicorp/terraform-provider-azurerm/services/mysql"
	"github.com/hashicorp/terraform-provider-azurerm/services/netapp"
	"github.com/hashicorp/terraform-provider-azurerm/services/network"
	"github.com/hashicorp/terraform-provider-azurerm/services/notificationhub"
	"github.com/hashicorp/terraform-provider-azurerm/services/policy"
	"github.com/hashicorp/terraform-provider-azurerm/services/portal"
	"github.com/hashicorp/terraform-provider-azurerm/services/postgres"
	"github.com/hashicorp/terraform-provider-azurerm/services/powerbi"
	"github.com/hashicorp/terraform-provider-azurerm/services/privatedns"
	"github.com/hashicorp/terraform-provider-azurerm/services/purview"
	"github.com/hashicorp/terraform-provider-azurerm/services/recoveryservices"
	"github.com/hashicorp/terraform-provider-azurerm/services/redis"
	"github.com/hashicorp/terraform-provider-azurerm/services/redisenterprise"
	"github.com/hashicorp/terraform-provider-azurerm/services/relay"
	"github.com/hashicorp/terraform-provider-azurerm/services/resource"
	"github.com/hashicorp/terraform-provider-azurerm/services/search"
	"github.com/hashicorp/terraform-provider-azurerm/services/securitycenter"
	"github.com/hashicorp/terraform-provider-azurerm/services/sentinel"
	"github.com/hashicorp/terraform-provider-azurerm/services/servicebus"
	"github.com/hashicorp/terraform-provider-azurerm/services/servicefabric"
	"github.com/hashicorp/terraform-provider-azurerm/services/servicefabricmanaged"
	"github.com/hashicorp/terraform-provider-azurerm/services/signalr"
	"github.com/hashicorp/terraform-provider-azurerm/services/springcloud"
	"github.com/hashicorp/terraform-provider-azurerm/services/sql"
	"github.com/hashicorp/terraform-provider-azurerm/services/storage"
	"github.com/hashicorp/terraform-provider-azurerm/services/streamanalytics"
	"github.com/hashicorp/terraform-provider-azurerm/services/subscription"
	"github.com/hashicorp/terraform-provider-azurerm/services/synapse"
	"github.com/hashicorp/terraform-provider-azurerm/services/trafficmanager"
	"github.com/hashicorp/terraform-provider-azurerm/services/videoanalyzer"
	"github.com/hashicorp/terraform-provider-azurerm/services/vmware"
	"github.com/hashicorp/terraform-provider-azurerm/services/web"
)

//go:generate go run ../tools/generator-services/main.go -path=../../

func SupportedTypedServices() []sdk.TypedServiceRegistration {
	return []sdk.TypedServiceRegistration{
		aadb2c.Registration{},
		apimanagement.Registration{},
		appconfiguration.Registration{},
		appservice.Registration{},
		batch.Registration{},
		bot.Registration{},
		consumption.Registration{},
		containers.Registration{},
		costmanagement.Registration{},
		disks.Registration{},
		eventhub.Registration{},
		keyvault.Registration{},
		loadbalancer.Registration{},
		loadtest.Registration{},
		mssql.Registration{},
		policy.Registration{},
		resource.Registration{},
		sentinel.Registration{},
		servicefabricmanaged.Registration{},
		streamanalytics.Registration{},
		web.Registration{},
	}
}

func SupportedUntypedServices() []sdk.UntypedServiceRegistration {
	return func() []sdk.UntypedServiceRegistration {
		out := []sdk.UntypedServiceRegistration{
			advisor.Registration{},
			analysisservices.Registration{},
			apimanagement.Registration{},
			appconfiguration.Registration{},
			springcloud.Registration{},
			applicationinsights.Registration{},
			attestation.Registration{},
			authorization.Registration{},
			automation.Registration{},
			azurestackhci.Registration{},
			batch.Registration{},
			billing.Registration{},
			blueprints.Registration{},
			bot.Registration{},
			cdn.Registration{},
			cognitive.Registration{},
			communication.Registration{},
			compute.Registration{},
			confidentialledger.Registration{},
			connections.Registration{},
			containers.Registration{},
			consumption.Registration{},
			cosmos.Registration{},
			customproviders.Registration{},
			databricks.Registration{},
			datafactory.Registration{},
			databasemigration.Registration{},
			databoxedge.Registration{},
			dataprotection.Registration{},
			datashare.Registration{},
			desktopvirtualization.Registration{},
			devtestlabs.Registration{},
			digitaltwins.Registration{},
			dns.Registration{},
			domainservices.Registration{},
			elastic.Registration{},
			eventgrid.Registration{},
			eventhub.Registration{},
			firewall.Registration{},
			frontdoor.Registration{},
			hpccache.Registration{},
			hsm.Registration{},
			hdinsight.Registration{},
			healthcare.Registration{},
			iothub.Registration{},
			iotcentral.Registration{},
			keyvault.Registration{},
			kusto.Registration{},
			legacy.Registration{},
			loadbalancer.Registration{},
			loganalytics.Registration{},
			logic.Registration{},
			logz.Registration{},
			machinelearning.Registration{},
			maintenance.Registration{},
			managedapplications.Registration{},
			lighthouse.Registration{},
			managementgroup.Registration{},
			maps.Registration{},
			mariadb.Registration{},
			media.Registration{},
			mixedreality.Registration{},
			monitor.Registration{},
			msi.Registration{},
			mssql.Registration{},
			mysql.Registration{},
			netapp.Registration{},
			network.Registration{},
			notificationhub.Registration{},
			policy.Registration{},
			portal.Registration{},
			postgres.Registration{},
			powerbi.Registration{},
			privatedns.Registration{},
			purview.Registration{},
			recoveryservices.Registration{},
			redis.Registration{},
			redisenterprise.Registration{},
			relay.Registration{},
			resource.Registration{},
			search.Registration{},
			securitycenter.Registration{},
			sentinel.Registration{},
			servicebus.Registration{},
			servicefabric.Registration{},
			signalr.Registration{},
			sql.Registration{},
			storage.Registration{},
			streamanalytics.Registration{},
			subscription.Registration{},
			synapse.Registration{},
			iottimeseriesinsights.Registration{},
			trafficmanager.Registration{},
			videoanalyzer.Registration{},
			vmware.Registration{},
			web.Registration{},
		}
		return out
	}()
}
